### ISSUE TITLE
Assersion failed while decompiling

### ISSUE THREAD

**Issue by buggedbeatle998** [krzys-h/UndertaleModTool#1127]
### Describe the bug

Whenever I edit anything in SCR_TEXT e.g. change a string, then I decompile it, it replaces the code with this error message:

/* EXCEPTION!
   System.Exception: Assertion failed! temp != switchEnd
   at UndertaleModLib.Util.DebugUtil.Assert(Boolean expr, String msg) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Util\DebugUtil.cs:line 16
   at UndertaleModLib.Decompiler.Decompiler.HLDecompileBlocks(DecompileContext context, Block& block, Dictionary`2 blocks, Dictionary`2 loops, Dictionary`2 reverseDominators, List`1 alreadyVisited, Block currentLoop, Block stopAt, Block breakTo, Boolean decompileTheLoop, UInt32 depth) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3348
   at UndertaleModLib.Decompiler.Decompiler.HLDecompile(DecompileContext context, Dictionary`2 blocks, Block entryPoint, Block rootExitPoint) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3466
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, GlobalDecompileContext globalContext) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3556
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass31_0.<DecompileCode>b__1() in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 444
*/

It doesn't happen on any other script, please help, what am I doing wrong?
https://drive.google.com/file/d/1t1nZlpzMuXUGTv3A-TPUpw-vS9munVPv/view?usp=sharing 

### Reproducing steps

1. open the data.win
2. go to SCR_TEXT in scripts
3. edit any string
4. ctrl + s
5. error message

### Setup Details

1. UndertaleModTool_v0.4.0.4
2. Windows 10
3. Undertale

**Comment by Jacky720** [comment]
Kindly remove the Google Drive link, we all have Undertale already and the data.win contains so much game data that it's tantamount to piracy. Rules are rules.

Can you try updating to the bleeding edge? 0.4.0.4 is several months old now, it might help.

**Comment by buggedbeatle998** [comment]
sorry, I didn't know

**Comment by Jacky720** [comment]
No worries. Any luck with updating?

**Comment by buggedbeatle998** [comment]
no unfortunately not

**Comment by buggedbeatle998** [comment]
The thing is, my backup data.win can decompile. But that's so far back that it's no use. It only recently stopped working

**Comment by buggedbeatle998** [comment]
@Jacky720 Ok, I firgured out what was wrong. I accidently deleted a "break" statement. Anyway thanks for opening my my eyes to the bleeding edge build.
