### ISSUE TITLE
not compiling code for deltarune

### ISSUE THREAD

**Issue by Unrealistic-games** [krzys-h/UndertaleModTool#1165]
### Describe the bug

When i try to compile an edit to a code it give this response on the newest build
`/* EXCEPTION!
   System.InvalidOperationException: The stack got misaligned? Error 2: Attempted to duplicate 16 bytes, only found 4
   at UndertaleModLib.Decompiler.Decompiler.DecompileFromBlock(DecompileContext context, Dictionary 2 blocks, Block block, List 1 tempvars, Stack 1 workQueue) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 2052
   at UndertaleModLib.Decompiler.Decompiler.DecompileFromBlock(DecompileContext context, Dictionary 2 blocks, Block block) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 2613
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, GlobalDecompileContext globalContext) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3769
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass36_0.<DecompileCode>b__1() in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 530
*/`
[Build at time of bug](https://github.com/krzys-h/UndertaleModTool/releases/tag/0.5.0.0)

### Reproducing steps

1. Open The deltarune data.win
2. edit a script EG gml_GlobalScript_scr_encountersetup_ch1
3. compile the script 
4. It replies with that

img for proof
[image](https://user-images.githubusercontent.com/112056127/216748598-507198da-2362-4d3d-85a0-afc97dfc08cf.png)

### Setup Details

1. Version of Undertale mod tool: [v0.5.0.0](https://github.com/krzys-h/UndertaleModTool/releases/tag/0.5.0.0)
2. Windows 10
3. Deltarune

**Comment by Unrealistic-games** [comment]
I figured it out the usb i was running it off of was corrupting
