### ISSUE TITLE
Failed to compile: Reentered block with different amount of vars on stack

### ISSUE THREAD

**Issue by te-agma-at** [krzys-h/UndertaleModTool#1216]
### Describe the bug

When editing code to include an if statement in an "else" block, it stops compiling and prints this error.

```
/* EXCEPTION!
   System.Exception: Reentered block with different amount of vars on stack (Entry: 2, Actual Count: 0)
   at UndertaleModLib.Decompiler.Decompiler.DecompileFromBlock(DecompileContext context, Dictionary`2 blocks, Block block, List`1 tempvars, Stack`1 workQueue) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 1943
   at UndertaleModLib.Decompiler.Decompiler.DecompileFromBlock(DecompileContext context, Dictionary`2 blocks, Block block) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 2613
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, GlobalDecompileContext globalContext) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3769
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass36_0.<DecompileCode>b__1() in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 530
*/
```

### Reproducing steps

1. Go into the Code Editor
2. Add an if statement (NOT EMPTY) inside of an "else" block
3. Error reproduced

### Setup Details

1. UndertaleModTool v0.5.0.0
2. Operating System: Windows 11
3. Game I was trying to mod: Pizza Tower

**Comment by te-agma-at** [comment]
Thanks! I will use the Bleeding Edge version from now on.
