### ISSUE TITLE
Commands `info` and `dump` throw an exception when `UndertaleData.Code` is null

### ISSUE THREAD

**Issue by rekyuu** [krzys-h/UndertaleModTool#1465]
### Describe the bug

Not too familiar with GameMaker personally so I'm not sure what could cause this.

In attempting to dump code from the HoloCure game, an exception is thrown. While debugging the process it appears that the exception is thrown when `Data.Code` tries to get read but the value is null. This probably just needs a default value of an empty list in the object or a null guard where necessary.

For the `info` command: https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModCli/Program.cs#L575  
For the `dump --code` command: https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModCli/Program.cs#L345

I'm unsure if this is an issue is with the `data.win` file, or if the game is compiled in such a way that code cannot be dumped.

### Reproducing steps

<details>
<summary>info command output</summary>

```
/home/rekyuu/src/UndertaleModTool/UndertaleModCli/bin/Debug/net6.0/UndertaleModCli info /home/rekyuu/Downloads/HoloCure/data.win --verbose
Trying to load file: '/home/rekyuu/Downloads/HoloCure/data.win'
[MESSAGE]: Counting objects of chunk GEN8
[MESSAGE]: Counting objects of chunk OPTN
[MESSAGE]: Counting objects of chunk LANG
[MESSAGE]: Counting objects of chunk EXTN
[MESSAGE]: Counting objects of chunk SOND
[MESSAGE]: Counting objects of chunk AGRP
[MESSAGE]: Counting objects of chunk SPRT
[MESSAGE]: Counting objects of chunk BGND
[MESSAGE]: Counting objects of chunk PATH
[MESSAGE]: Counting objects of chunk SCPT
[MESSAGE]: Counting objects of chunk GLOB
[MESSAGE]: Counting objects of chunk SHDR
[MESSAGE]: Counting objects of chunk FONT
[MESSAGE]: Counting objects of chunk TMLN
[MESSAGE]: Counting objects of chunk OBJT
[MESSAGE]: Counting objects of chunk FEDS
[MESSAGE]: Counting objects of chunk ACRV
[MESSAGE]: Counting objects of chunk SEQN
[MESSAGE]: Counting objects of chunk TAGS
[MESSAGE]: Counting objects of chunk ROOM
[MESSAGE]: Counting objects of chunk DAFL
[MESSAGE]: Counting objects of chunk EMBI
[MESSAGE]: Counting objects of chunk PSEM
[MESSAGE]: Counting objects of chunk PSYS
[MESSAGE]: Counting objects of chunk TPAG
[MESSAGE]: Counting objects of chunk TGIN
[MESSAGE]: Counting objects of chunk FEAT
[MESSAGE]: Counting objects of chunk STRG
[MESSAGE]: Counting objects of chunk TXTR
[MESSAGE]: Counting objects of chunk AUDO
[MESSAGE]: Reading chunk GEN8
[MESSAGE]: Reading chunk OPTN
[MESSAGE]: Reading chunk LANG
[MESSAGE]: Reading chunk EXTN
[MESSAGE]: Reading chunk SOND
[MESSAGE]: Reading chunk AGRP
[MESSAGE]: Reading chunk SPRT
[MESSAGE]: Reading chunk BGND
[MESSAGE]: Reading chunk PATH
[MESSAGE]: Reading chunk SCPT
[MESSAGE]: Reading chunk GLOB
[MESSAGE]: Reading chunk SHDR
[MESSAGE]: Reading chunk FONT
[MESSAGE]: Reading chunk TMLN
[MESSAGE]: Reading chunk OBJT
[MESSAGE]: Reading chunk FEDS
[MESSAGE]: Reading chunk ACRV
[MESSAGE]: Reading chunk SEQN
[MESSAGE]: Reading chunk TAGS
[MESSAGE]: Reading chunk ROOM
[MESSAGE]: Reading chunk DAFL
[MESSAGE]: Reading chunk EMBI
[MESSAGE]: Reading chunk PSEM
[MESSAGE]: Reading chunk PSYS
[MESSAGE]: Reading chunk TPAG
[MESSAGE]: Reading chunk TGIN
[MESSAGE]: Reading chunk FEAT
[MESSAGE]: Reading chunk STRG
[MESSAGE]: Reading chunk TXTR
[MESSAGE]: Reading chunk AUDO
[MESSAGE]: Resolving resource IDs...
Output directory has been set to /home/rekyuu/Downloads/HoloCure
Quick Information:
Project Name - "HoloCure"
Is GMS2 - True
Is YYC - True
Bytecode version - 17
Configuration name - "Itch"
299 Sounds, 2472 Sprites, 1 Backgrounds
0 Paths, 12984 Scripts, 44 Shaders
22 Fonts, 0 Timelines, 382 Game Objects
22 Rooms, 3 Extensions, 6291 Texture Page Items
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at UndertaleModCli.Program.CliQuickInfo() in /home/rekyuu/src/UndertaleModTool/UndertaleModCli/Program.cs:line 575
   at UndertaleModCli.Program.Info(InfoOptions options) in /home/rekyuu/src/UndertaleModTool/UndertaleModCli/Program.cs:line 322
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
</details>

<details>
<summary>dump command output</summary>

```
/home/rekyuu/src/UndertaleModTool/UndertaleModCli/bin/Debug/net6.0/UndertaleModCli dump /home/rekyuu/Downloads/HoloCure/data.win --code UMT_DUMP_ALL --output /home/rekyuu/Downloads/HoloCure-decompile --verbose
Trying to load file: '/home/rekyuu/Downloads/HoloCure/data.win'
[MESSAGE]: Counting objects of chunk GEN8
[MESSAGE]: Counting objects of chunk OPTN
[MESSAGE]: Counting objects of chunk LANG
[MESSAGE]: Counting objects of chunk EXTN
[MESSAGE]: Counting objects of chunk SOND
[MESSAGE]: Counting objects of chunk AGRP
[MESSAGE]: Counting objects of chunk SPRT
[MESSAGE]: Counting objects of chunk BGND
[MESSAGE]: Counting objects of chunk PATH
[MESSAGE]: Counting objects of chunk SCPT
[MESSAGE]: Counting objects of chunk GLOB
[MESSAGE]: Counting objects of chunk SHDR
[MESSAGE]: Counting objects of chunk FONT
[MESSAGE]: Counting objects of chunk TMLN
[MESSAGE]: Counting objects of chunk OBJT
[MESSAGE]: Counting objects of chunk FEDS
[MESSAGE]: Counting objects of chunk ACRV
[MESSAGE]: Counting objects of chunk SEQN
[MESSAGE]: Counting objects of chunk TAGS
[MESSAGE]: Counting objects of chunk ROOM
[MESSAGE]: Counting objects of chunk DAFL
[MESSAGE]: Counting objects of chunk EMBI
[MESSAGE]: Counting objects of chunk PSEM
[MESSAGE]: Counting objects of chunk PSYS
[MESSAGE]: Counting objects of chunk TPAG
[MESSAGE]: Counting objects of chunk TGIN
[MESSAGE]: Counting objects of chunk FEAT
[MESSAGE]: Counting objects of chunk STRG
[MESSAGE]: Counting objects of chunk TXTR
[MESSAGE]: Counting objects of chunk AUDO
[MESSAGE]: Reading chunk GEN8
[MESSAGE]: Reading chunk OPTN
[MESSAGE]: Reading chunk LANG
[MESSAGE]: Reading chunk EXTN
[MESSAGE]: Reading chunk SOND
[MESSAGE]: Reading chunk AGRP
[MESSAGE]: Reading chunk SPRT
[MESSAGE]: Reading chunk BGND
[MESSAGE]: Reading chunk PATH
[MESSAGE]: Reading chunk SCPT
[MESSAGE]: Reading chunk GLOB
[MESSAGE]: Reading chunk SHDR
[MESSAGE]: Reading chunk FONT
[MESSAGE]: Reading chunk TMLN
[MESSAGE]: Reading chunk OBJT
[MESSAGE]: Reading chunk FEDS
[MESSAGE]: Reading chunk ACRV
[MESSAGE]: Reading chunk SEQN
[MESSAGE]: Reading chunk TAGS
[MESSAGE]: Reading chunk ROOM
[MESSAGE]: Reading chunk DAFL
[MESSAGE]: Reading chunk EMBI
[MESSAGE]: Reading chunk PSEM
[MESSAGE]: Reading chunk PSYS
[MESSAGE]: Reading chunk TPAG
[MESSAGE]: Reading chunk TGIN
[MESSAGE]: Reading chunk FEAT
[MESSAGE]: Reading chunk STRG
[MESSAGE]: Reading chunk TXTR
[MESSAGE]: Reading chunk AUDO
[MESSAGE]: Resolving resource IDs...
Output directory has been set to /home/rekyuu/Downloads/HoloCure-decompile
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at UndertaleModCli.Program.Dump(DumpOptions options) in /home/rekyuu/src/UndertaleModTool/UndertaleModCli/Program.cs:line 345
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
</details>

### Setup Details

1. UndertaleModTool version: 7b876ad457eca5cdd69957dc02ef57a569412e5e
2. Operating system: Arch Linux 6.4.11-zen2-1-zen
3. GameMaker Game: https://kay-yu.itch.io/holocure

**Comment by Archie-osu** [comment]
The game is YYC, the CODE chunk doesn't exist in those games.
I second there being a check for this.
