### ISSUE TITLE
gml_Object_obj_settingsmenu_Draw_0 fails to decompile after running the BorderEnabler script

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#209]
The "BorderEnabler" script causes this error to appear when attempting to decompile gml_Object_obj_settingsmenu_Draw_0:
```EXCEPTION!
System.Exception: Reentered block with different amount of vars on stack
   at UndertaleModLib.Decompiler.Decompiler.DecompileFromBlock(DecompileContext context, Block block, List`1 tempvars, Stack`1 workQueue) in C:\Users\USER\Downloads\UndertaleModTool-07697ae7f.zip\UndertaleModLib\Decompiler\Decompiler.cs:line 1194
   at UndertaleModLib.Decompiler.Decompiler.DecompileFromBlock(DecompileContext context, Block block) in C:\Users\USER\Downloads\UndertaleModTool-07697ae7f.zip\UndertaleModLib\Decompiler\Decompiler.cs:line 1537
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, DecompileContext context) in C:\Users\USER\Downloads\UndertaleModTool-07697ae7f.zip\UndertaleModLib\Decompiler\Decompiler.cs:line 2575
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass11_0.<DecompileCode>b__0() in C:\Users\USER\Downloads\UndertaleModTool-07697ae7f.zip\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 295
```

This is probably related to @krzys-h 's comment `` // TODO: yeah, I'm leaving junk on the stack, I don't want to waste time figuring out how to avoid that in an odd number of instructions :P`` at line 97 of "BorderEnabler.csx".

**Comment by colinator27** [comment]
Does this issue still exist?

**Comment by Kneesnap** [comment]
Yes

**Comment by Grossley** [comment]
Yes it does.

**Comment by Grossley** [comment]
Merged into more recent issue.
