### ISSUE TITLE
[Stack Empty] Issue #1

### ISSUE THREAD

**Issue by KadePcGames** [krzys-h/UndertaleModTool#210]
Game Name: Unforgiven
Data.win: https://cdn.discordapp.com/attachments/583466397573709834/604800050291539986/data.win
Stack Trace:

EXCEPTION!
System.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Pop()
   at UndertaleModLib.Decompiler.Decompiler.DecompileFromBlock(DecompileContext context, Block block, List`1 tempvars, Stack`1 workQueue) in C:\Users\kadep\Documents\UndertaleModTool-dev\UndertaleModLib\Decompiler\Decompiler.cs:line 1239
   at UndertaleModLib.Decompiler.Decompiler.DecompileFromBlock(DecompileContext context, Block block) in C:\Users\kadep\Documents\UndertaleModTool-dev\UndertaleModLib\Decompiler\Decompiler.cs:line 1539
   at UndertaleModLib.Decompiler.Decompiler.FunctionCall.DoTypePropagation(DecompileContext context, AssetIDType suggestedType) in C:\Users\kadep\Documents\UndertaleModTool-dev\UndertaleModLib\Decompiler\Decompiler.cs:line 995
   at UndertaleModLib.Decompiler.Decompiler.DoTypePropagation(DecompileContext context, Dictionary`2 blocks) in C:\Users\kadep\Documents\UndertaleModTool-dev\UndertaleModLib\Decompiler\Decompiler.cs:line 2596
   at UndertaleModLib.Decompiler.Decompiler.FunctionCall.DoTypePropagation(DecompileContext context, AssetIDType suggestedType) in C:\Users\kadep\Documents\UndertaleModTool-dev\UndertaleModLib\Decompiler\Decompiler.cs:line 996
   at UndertaleModLib.Decompiler.Decompiler.DoTypePropagation(DecompileContext context, Dictionary`2 blocks) in C:\Users\kadep\Documents\UndertaleModTool-dev\UndertaleModLib\Decompiler\Decompiler.cs:line 2596
   at UndertaleModLib.Decompiler.Decompiler.FunctionCall.DoTypePropagation(DecompileContext context, AssetIDType suggestedType) in C:\Users\kadep\Documents\UndertaleModTool-dev\UndertaleModLib\Decompiler\Decompiler.cs:line 996
   at UndertaleModLib.Decompiler.Decompiler.DoTypePropagation(DecompileContext context, Dictionary`2 blocks) in C:\Users\kadep\Documents\UndertaleModTool-dev\UndertaleModLib\Decompiler\Decompiler.cs:line 2596
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, DecompileContext context) in C:\Users\kadep\Documents\UndertaleModTool-dev\UndertaleModLib\Decompiler\Decompiler.cs:line 2578
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass11_0.<DecompileCode>b__0() in C:\Users\kadep\Documents\UndertaleModTool-dev\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 295

In: gml_Object_obj_player_Step_0

Go gettem kneesnap.

**Comment by Grossley** [comment]
Could not reproduce in 96d3e6a and is probably the result of an old version of UndertaleModTool. This should be closed.

**Comment by Kneesnap** [comment]
This issue may be one I just recently looked into and fixed regarding dup.l 0

**Comment by KadePcGames** [comment]
@Grossley Maybe, kneesnap contacted me in discord about it.

**Comment by Grossley** [comment]
> 
> 
> @Grossley Maybe, kneesnap contacted me in discord about it.

@KadePcGames I could not reproduce the issue in 96d3e6a . Unless there is some other issue not described here this should be closed because this bug does not exist on the newest version of UndertaleModTool.

**Comment by KadePcGames** [comment]
@Grossley chill ur tits dude, just makin an issue here. You dont got to get all gamered up over here.
