### ISSUE TITLE
Attempting to compile an "EXCEPTION!" message causes UndertaleModTool to crash.

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#212]
Attempting to compile this message on accident caused UndertaleModTool to crash:

```EXCEPTION!
System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Decimal..ctor(Double value)
   at System.Decimal.op_Explicit(Double value)
   at UndertaleModLib.Decompiler.Decompiler.ExpressionConstant.ToString(DecompileContext context) in C:\Users\USER\Desktop\UndertaleModTool-96d3e6a38c\UndertaleModLib\Decompiler\Decompiler.cs:line 356
   at UndertaleModLib.Decompiler.Decompiler.ExpressionCompare.ToString(DecompileContext context) in C:\Users\USER\Desktop\UndertaleModTool-96d3e6a38c\UndertaleModLib\Decompiler\Decompiler.cs:line 661
   at UndertaleModLib.Decompiler.Decompiler.ExpressionTwoSymbol.ToString(DecompileContext context) in C:\Users\USER\Desktop\UndertaleModTool-96d3e6a38c\UndertaleModLib\Decompiler\Decompiler.cs:line 586
   at UndertaleModLib.Decompiler.Decompiler.AssignmentStatement.ToString(DecompileContext context) in C:\Users\USER\Desktop\UndertaleModTool-96d3e6a38c\UndertaleModLib\Decompiler\Decompiler.cs:line 874
   at UndertaleModLib.Decompiler.Decompiler.BlockHLStatement.ToString(DecompileContext context, Boolean canSkipBrackets, Boolean forceSkipBrackets) in C:\Users\USER\Desktop\UndertaleModTool-96d3e6a38c\UndertaleModLib\Decompiler\Decompiler.cs:line 1703
   at UndertaleModLib.Decompiler.Decompiler.IfHLStatement.ToString(DecompileContext context) in C:\Users\USER\Desktop\UndertaleModTool-96d3e6a38c\UndertaleModLib\Decompiler\Decompiler.cs:line 1869
   at UndertaleModLib.Decompiler.Decompiler.BlockHLStatement.ToString(DecompileContext context, Boolean canSkipBrackets, Boolean forceSkipBrackets) in C:\Users\USER\Desktop\UndertaleModTool-96d3e6a38c\UndertaleModLib\Decompiler\Decompiler.cs:line 1703
   at UndertaleModLib.Decompiler.Decompiler.IfHLStatement.ToString(DecompileContext context) in C:\Users\USER\Desktop\UndertaleModTool-96d3e6a38c\UndertaleModLib\Decompiler\Decompiler.cs:line 1858
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, DecompileContext context) in C:\Users\USER\Desktop\UndertaleModTool-96d3e6a38c\UndertaleModLib\Decompiler\Decompiler.cs:line 2592
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass11_0.<DecompileCode>b__0() in C:\Users\USER\Desktop\UndertaleModTool-96d3e6a38c\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 296
```

This triggered a break at line 1402 of Parser.cs while debugging.

**Comment by colinator27** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/209655a957ec64484d5ca24c2be030fbe4244bd3
