### ISSUE TITLE
UndertaleModCli: System.NotSupportedException: Can't create a metadata reference to an assembly without location.

### ISSUE THREAD

**Issue by gurgalex** [krzys-h/UndertaleModTool#646]
Downloaded the x64 version.
OS: Windows 10 64 bit
https://github.com/krzys-h/UndertaleModTool/actions/runs/1349846561

Also tried with the .net bundled and copying the data.win file to the same directory as the cli exe ` .\UndertaleModCli.exe data.win`  same error.

```
PS C:\Users\alex\Downloads\cli_win_x64> .\UndertaleModCli.exe "C:\Program Files (x86)\Steam\steamapps\common\Siralim Ultimate\data.win"
Trying to load file C:\Program Files (x86)\Steam\steamapps\common\Siralim Ultimate\data.win
An exception has occurred in UndertaleModCli:
System.NotSupportedException: Can't create a metadata reference to an assembly without location.
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.CreateReferenceFromAssembly(Assembly assembly)
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.<>c__DisplayClass4_0`2.<SelectChecked>b__0(T item)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.AddRangeChecked[T](ArrayBuilder`1 builder, IEnumerable`1 items, String parameterName)
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.ConcatChecked[T](ImmutableArray`1 existing, IEnumerable`1 items, String parameterName)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.AddReferences(IEnumerable`1 references)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.AddReferences(IEnumerable`1 references)
   at UndertaleModCli.Program.CliMain(String[] args)

```Report this as a bug.
PS C:\Users\alex\Downloads\cli_win_x64>

**Comment by gurgalex** [comment]
Okay, so building from source works on my local machine (debug and release .net 5.0 versions)
(needed to add the https://api.nuget.org/v3/index.json as an endpoint)

**Comment by gurgalex** [comment]
I think it may be that the DLLs (and maybe other stuff) isn't being bundled with the exe release.
Here's my folder output on a release build
![image](https://user-images.githubusercontent.com/28968644/137605997-c21bab5a-e969-44cf-b35b-708b9347e6b2.png)


this is what it looks like from the CI zip file (no DLLs)
![image](https://user-images.githubusercontent.com/28968644/137606023-b3592115-13f6-4c01-8038-8a8b417ac3b4.png)

**Comment by gurgalex** [comment]
Okay, it may not be that, the DLLs are probably inside the 11MB exe instead of alongside it (like in my release folder)

**Comment by gurgalex** [comment]
the build from this command fails with the same error as reported.
`dotnet publish UndertaleModCli -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true --output cli_win_x64`

**Comment by Grossley** [comment]
It is very possible that the commands to build the file are incorrect.

**Comment by Grossley** [comment]
Sounds good make pull request removing it

**Comment by gurgalex** [comment]
Workaround made in #652
