### ISSUE TITLE
CLI - Inconsistent usage of "-d"

### ISSUE THREAD

**Issue by Miepee** [krzys-h/UndertaleModTool#692]
Got an error while trying to execute a script and save the result.

Executed Cli like this: `.\UndertaleModCli.exe load "C:\Users\Idiot\AppData\Local\Temp/The Horde Multitroid - Kopie.zip/extract/data.win" -s "C:\Users\Idiot\source\repos\AM2RPortHelper -test\AM2RPortHelper\bin\Debug\net5.0/utils/bc16AndRemoveFunctions.csx" -d "C:\Users\Idiot\AppData\Local\Temp/The Horde Multitroid - Kopie.zip/extract/data.win"`

This is the exception I got:
```
Script file not found or cannot be read.
System.IO.FileNotFoundException: Could not find file 'C:\Users\Idiot\source\repos\AM2RPortHelper -test\AM2RPortHelper\utils\UTMTCli\-d'.
File name: 'C:\Users\Idiot\source\repos\AM2RPortHelper -test\AM2RPortHelper\utils\UTMTCli\-d'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at UndertaleModCli.Program.RunCodeFile(String path) in C:\Users\Idiot\source\repos\UndertaleModTool\UndertaleModCli\Program.cs:line 388
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (1,6): error CS1002: ; expected
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync(String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at UndertaleModCli.Program.RunCodeLine(String line) in C:\Users\Idiot\source\repos\UndertaleModTool\UndertaleModCli\Program.cs:line 357
   ````

**Comment by Miepee** [comment]
Using `--dest` instead of `-d` fixes this apparently. After looking at the code more, it seems like the "save" option for loading a data.win file [does not have that shortcut](https://github.com/krzys-h/UndertaleModTool/blob/0eae4e2ed85d103e7bd4f1cc431255cfebe6f161/UndertaleModCli/Program.cs#L196), while the one for creating a [blank data.win file does](https://github.com/krzys-h/UndertaleModTool/blob/0eae4e2ed85d103e7bd4f1cc431255cfebe6f161/UndertaleModCli/Program.cs#L205).

In which case, I'd ask for consistency between those two options.
