### ISSUE TITLE
"Do" statements

### ISSUE THREAD

**Issue by Yule42** [krzys-h/UndertaleModTool#729]
Ex: 
`i = 0;
do
{ i++; }
until (i > 5)`

once compiled becomes
/* EXCEPTION!
   System.NullReferenceException: Object reference not set to an instance of an object.
   at UndertaleModLib.Decompiler.Decompiler.ComputeReverseDominators(Dictionary\`2 blocks, Block entryBlock) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3004
   at UndertaleModLib.Decompiler.Decompiler.HLDecompile(DecompileContext context, Dictionary\`2 blocks, Block entryPoint, Block rootExitPoint) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3344
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, GlobalDecompileContext globalContext) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3436
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass29_0.<DecompileCode>b__1() in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 388
*/

**Comment by BenjaminUrquhart** [comment]
Known: https://github.com/krzys-h/UndertaleModTool/issues/671

**Comment by colinator27** [comment]
Closing as duplicate
