### ISSUE TITLE
Decompiler issue on AM2R

### ISSUE THREAD

**Issue by Miepee** [krzys-h/UndertaleModTool#798]
UTMT 0.4.0.4 has a slight issue trying to decompile AM2R. `gml_Script_spawn_random_septogg` in particular.
```
/* EXCEPTION!
   System.NullReferenceException: Object reference not set to an instance of an object.
   at UndertaleModLib.Decompiler.Decompiler.ComputeReverseDominators(Dictionary`2 blocks, Block entryBlock) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3124
   at UndertaleModLib.Decompiler.Decompiler.HLDecompile(DecompileContext context, Dictionary`2 blocks, Block entryPoint, Block rootExitPoint) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3466
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, GlobalDecompileContext globalContext) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3556
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass31_0.<DecompileCode>b__1() in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 444
*/
```

Source code for that script can be found [here](https://github.com/AM2R-Community-Developers/AM2R-Community-Updates/blob/main/scripts/spawn_random_septogg.gml)

**Comment by Miepee** [comment]
For reference, DogScepter *is* able to decompile it correctly.

To be more exact about the issue, it happens in this do while loop in Decompiler.cs (starting line 3100)
```cs
            do
            {
                changed = false;
                for (int i = 0; i < blockList.Length; i++)
                {
                    if (i == entryBlockId)
                        continue;

                    Block b = blockList[i];

                    IEnumerable<Block> e;
                    if (b.conditionalExit)
                    {
                        reverseUse2[0] = b.nextBlockTrue;
                        reverseUse2[1] = b.nextBlockFalse;
                        e = reverseUse2;
                    }
                    else
                    {
                        reverseUse1[0] = b.nextBlockTrue;
                        e = reverseUse1;
                    }

                    foreach (Block pred in e)
                        changed |= dominators[i].And(dominators[pred._CachedIndex], i);
                }
            } while (changed);
```
Issue occurs on i==46.
`b` gets this value assigned:
![image](https://user-images.githubusercontent.com/38186597/160421693-378169bd-c263-425e-b3e9-b595e453bbbd.png)
And due to `nextBlockTrue` and `nextBlockFalse` both being null, that screws with `e`, as it gets this assignment then:
![image](https://user-images.githubusercontent.com/38186597/160422100-d85ab6fb-5e9f-4fa7-968f-9a710449a686.png)
The foreach goes through `e`, assigns `null` to `pred`, and then crashes while trying to get `pred._CachedIndex`.
